<a href="https://colab.research.google.com/github/mahinkhan1408/NID-Data-extraction-project/blob/main/Numpy_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as  np

zer=   np.zeros(10)

print(zer)

num= [1,2,3,4,5,6,67]

array1 =  np.array(num)
print(array1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 1  2  3  4  5  6 67]


In [ ]:
one_array = np.ones(100)
print(one_array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]


In [ ]:
rando = np.arange(1,50,2)  # dont think like "arrange" , its 'arange'
print(rando)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]


In [ ]:
randomm=  np.random.randint(1,100,5)
print(randomm)


[25 42 78 65 51]


In [ ]:
randommatrix = np.random.rand(3,3)
print(randommatrix)

[[0.50413169 0.74371034 0.38731165]
 [0.74222572 0.70829555 0.16029698]
 [0.00717751 0.62662346 0.95091216]]


In [ ]:
shape = randommatrix.shape
print(shape)

(3, 3)


In [ ]:
size = randommatrix.size
print(size)

9


In [ ]:
dtype = randommatrix.dtype
print(dtype)

float64


In [ ]:
#dimension

print(randommatrix.ndim)

2


In [ ]:
array1= np.array([1,4,5,6,7])
array2= np.array([5,7,8,12,17])

sum = array1 + array2

print (sum)

mul= array1 * array2
#div

[ 6 11 13 18 24]


In [ ]:
# aggregation

mean = np.mean(array1)
print(mean)

#sum()
#max(), min()

4.6


In [ ]:
# we can perform boolean operation

greater_than = array1 > 3

print(greater_than)

[False  True  True  True  True]


In [ ]:
#broadcasting

result = array1 + 5
print(result)

[ 6  9 10 11 12]


**INDEXING and SLICING**

In [8]:
print(array1[-2])

6


In [11]:
#slicing a array
print(array1)
sliced= array1[1:4]  # last element wont be printed
print(sliced)

[1 4 5 6 7]
[4 5 6]


In [15]:
#step by 2

array= [1,2,3,45,5,6,7,7,8,9,9,23,4,5,6,7]
step_array = array[::2]  # this will provide the output of the list element one step ahead
print(step_array)

sarray = array[2::]
print(sarray) # this is showing every elements except the first two


sarray = array[5::]
print(sarray)


sarray = array[2::8] #only the
print(sarray)

[1, 3, 5, 7, 8, 9, 4, 6]
[3, 45, 5, 6, 7, 7, 8, 9, 9, 23, 4, 5, 6, 7]
[6, 7, 7, 8, 9, 9, 23, 4, 5, 6, 7]
[3, 9]


In [4]:
matrix =  np.array([[1,2,3],[4,5,6],[7,8,9]])

element = matrix[1,1]
print(element)

second = matrix[1,:] # will print second row
print(second)

col = matrix[:,1]
print(col)

5
[4 5 6]
[2 5 8]


In [6]:
# missing data management in numpy''
data = np.array ([1,2,3,np.nan, 4,5])
missing = np.isnan(data)
print(missing)
dataf = np.nan_to_num(data, nan = 100)
print(dataf)

[False False False  True False False]
[  1.   2.   3. 100.   4.   5.]


**Linear Algebra and Statistics**

* matrix multiplication and inversion
* Mean and standard deviation
*corelation

In [10]:
array1 = np.array([[1,2],[3,4]])
array2 = np.array([[3,5],[7,8]])

mul= np.dot(array1, array2) #matrix multiplication
print(mul)

invr = np.linalg.inv(array1)
print(invr) # inverse of the matrix (array1 )

eval, evect = np.linalg.eig(array1)  # eagen value and vector
#(w, v) (tuple of ndarray): This function returns a tuple consisting of two arrays:
print(eval)
print(evect)


[[17 21]
 [37 47]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [16]:
data1 = np.array([1,2,3,4,5])

mean= np.mean(data1)
print(mean)
stddev = np.std(data1)
print(stddev)


3.0
1.4142135623730951
[[1.         0.35804682]
 [0.35804682 1.        ]]


In [17]:

#correlation and coefficient

data2=  np.array([1,56,7,643,23])
cor=np.corrcoef(data1,data2)
print(cor)

[[1.         0.35804682]
 [0.35804682 1.        ]]


**Write DataFrames as file**

In [18]:
np.savetxt('output.csv',mul,delimiter=',') # output will be in csv



Write as binary file

In [19]:
np.save('output.npy',mul)

# to use the binary file

new_matrix = np.load('output.npy')

We can save it as excel also, for that we need to use pandas

In [25]:
import pandas as pd
df= pd.DataFrame(mul)
df.to_excel('output.xlsx0')