<a href="https://colab.research.google.com/github/mahinkhan1408/NID-Data-extraction-project/blob/main/Numpy_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as  np

zer=   np.zeros(10)

print(zer)

num= [1,2,3,4,5,6,67]

array1 =  np.array(num)
print(array1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 1  2  3  4  5  6 67]


In [4]:
one_array = np.ones(100)
print(one_array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]


In [9]:
rando = np.arange(1,50,2)  # dont think like "arrange" , its 'arange'
print(rando)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]


In [10]:
randomm=  np.random.randint(1,100,5)
print(randomm)


[25 42 78 65 51]


In [11]:
randommatrix = np.random.rand(3,3)
print(randommatrix)

[[0.50413169 0.74371034 0.38731165]
 [0.74222572 0.70829555 0.16029698]
 [0.00717751 0.62662346 0.95091216]]


In [13]:
shape = randommatrix.shape
print(shape)

(3, 3)


In [14]:
size = randommatrix.size
print(size)

9


In [15]:
dtype = randommatrix.dtype
print(dtype)

float64


In [17]:
#dimension

print(randommatrix.ndim)

2
